
//Immobilier
export const IMMO_GET_ALL = 'IMMO_GET_ALL' ;
export const IMMO_GET_ALL_SUCCESS = 'IMMO_GET_ALL_SUCCESS' ;
export const IMMO_GET_ALL_ERROR = 'IMMO_GET_ALL_ERROR' ;

/*
export const IMMO_GET_ONE = 'IMMO_GET_ONE' ;
export const IMMO_GET_ONE_SUCCESS = 'IMMO_GET_ONE_SUCCESS' ;
export const IMMO_GET_ONE_ERROR = 'IMMO_GET_ONE_ERROR' ;

export const IMMO_POST_FILTER = 'IMMO_POST_FILTER' ;
export const IMMO_POST_FILTER_SUCCESS = 'IMMO_POST_FILTER_SUCCESS' ;
export const IMMO_POST_FILTER_ERROR = 'IMMO_POST_FILTER_ERROR' ;

export const IMMO_POST_NUMBER_RESULTS = 'IMMO_POST_NUMBER_RESULTS' ;
export const IMMO_POST_NUMBER_RESULTS_SUCCESS = 'IMMO_POST_NUMBER_RESULTS_SUCCESS' ;
export const IMMO_POST_NUMBER_RESULTS_ERROR = 'IMMO_POST_NUMBER_RESULTS_ERROR' ;

export const IMMO_GET_LAST = 'IMMO_GET_LAST' ;
export const IMMO_GET_LAST_SUCCESS = 'IMMO_GET_LAST_SUCCESS' ;
export const IMMO_GET_LAST_ERROR = 'IMMO_GET_LAST_ERROR' ;

export const IMMO_POST_DISTINCT = 'IMMO_POST_DISTINCT'
export const IMMO_POST_DISTINCT_SUCCESS = 'IMMO_POST_DISTINCT_SUCCESS'
export const IMMO_POST_DISTINCT_ERROR = 'IMMO_POST_DISTINCT_ERROR'
*/
