//SAVE FILTERS
export const SAVE_FILTERS = 'SAVE_FILTERS'

//SAVE PAGE INFO
export const SAVE_PAGINATION = 'SAVE_PAGINATION'

//SAVE ELEMENT SCROLL POSITION
export const SAVE_ELEMENT_SCROLL_POSITION = 'SAVE_ELEMENT_SCROLL_POSITION'

//SAVE PAGE FROM
export const SAVE_COME_FROM = 'SAVE_COME_FROM'

//reset something in page
export const RESET_IN_PAGE = 'RESET_IN_PAGE'
