
/*-----------------Immobilier---------------------*/

//get all immo
export const IMMO_GET_ALL = 'IMMO_GET_ALL' ;
export const IMMO_GET_ALL_SUCCESS = 'IMMO_GET_ALL_SUCCESS' ;
export const IMMO_GET_ALL_ERROR = 'IMMO_GET_ALL_ERROR' ;

//get somes by filters
export const IMMO_GET_BY_FILTERS = 'IMMO_GET_BY_FILTERS' ;
export const IMMO_GET_BY_FILTERS_SUCCESS = 'IMMO_GET_BY_FILTERS_SUCCESS' ;
export const IMMO_GET_BY_FILTERS_ERROR = 'IMMO_GET_BY_FILTERS_ERROR' ;

//get one by id
export const IMMO_GET_ONE = 'IMMO_GET_ONE' ;
export const IMMO_GET_ONE_SUCCESS = 'IMMO_GET_ONE_SUCCESS' ;
export const IMMO_GET_ONE_ERROR = 'IMMO_GET_ONE_ERROR' ;

//reset somethinh in immo :
export const RESET_IN_IMMO = 'RESET_IN_IMMO'

/*
export const IMMO_POST_NUMBER_RESULTS = 'IMMO_POST_NUMBER_RESULTS' ;
export const IMMO_POST_NUMBER_RESULTS_SUCCESS = 'IMMO_POST_NUMBER_RESULTS_SUCCESS' ;
export const IMMO_POST_NUMBER_RESULTS_ERROR = 'IMMO_POST_NUMBER_RESULTS_ERROR' ;

export const IMMO_GET_LAST = 'IMMO_GET_LAST' ;
export const IMMO_GET_LAST_SUCCESS = 'IMMO_GET_LAST_SUCCESS' ;
export const IMMO_GET_LAST_ERROR = 'IMMO_GET_LAST_ERROR' ;

export const IMMO_POST_DISTINCT = 'IMMO_POST_DISTINCT'
export const IMMO_POST_DISTINCT_SUCCESS = 'IMMO_POST_DISTINCT_SUCCESS'
export const IMMO_POST_DISTINCT_ERROR = 'IMMO_POST_DISTINCT_ERROR'

*/
